/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio5;

import javax.swing.JOptionPane;

/**
 *
 * @author baltamar
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPolitica = new javax.swing.JTextField();
        txtSeguroSocial = new javax.swing.JTextField();
        txtSeguroForzoso = new javax.swing.JTextField();
        txtCajaAhorros = new javax.swing.JTextField();
        txtSueldoFinal = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESCUENTO SALARIAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setText("Sueldo base:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 210, -1));

        jLabel3.setText("Politica publica:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("Seguro social:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setText("Seguro forzoso:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel6.setText("Caja de ahorros:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Sueldo Final");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtPolitica.setEditable(false);
        jPanel1.add(txtPolitica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, -1));

        txtSeguroSocial.setEditable(false);
        jPanel1.add(txtSeguroSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        txtSeguroForzoso.setEditable(false);
        jPanel1.add(txtSeguroForzoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, -1));

        txtCajaAhorros.setEditable(false);
        jPanel1.add(txtCajaAhorros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 70, -1));

        txtSueldoFinal.setEditable(false);
        jPanel1.add(txtSueldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 270, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtCajaAhorros.setText("");
       txtPolitica.setText("");
       txtSeguroForzoso.setText("");
       txtSeguroSocial.setText("");
       txtSueldo.setText("");
       txtSueldoFinal.setText("");
       txtSueldo.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
         char c=evt.getKeyChar(); 
             
         if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume(); 
               } 
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        double sueldo,politica_publica,seguro_forzoso,seguro_social,caja_ahorros,op;
        String sueldo2,politica_publica2,seguro_forzoso2,seguro_social2,caja_ahorros2;
        
        if(txtSueldo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Digite sueldo"," error", JOptionPane.ERROR_MESSAGE);
            txtSueldo.requestFocusInWindow();
        }
        else{
            sueldo=Double.parseDouble(txtSueldo.getText());
            politica_publica=(sueldo*1)/100;
            seguro_social=(sueldo*4)/100;
            seguro_forzoso=(sueldo*0.5)/100;
            caja_ahorros=(sueldo*5)/100;
            op=politica_publica+seguro_forzoso+seguro_social+caja_ahorros;
            sueldo=sueldo-op;
            
            politica_publica2=String.valueOf(politica_publica);
            txtPolitica.setText(politica_publica2);
            seguro_social2=String.valueOf(seguro_social);
            txtSeguroSocial.setText(seguro_social2);
            seguro_forzoso2=String.valueOf(seguro_forzoso);
            txtSeguroForzoso.setText(seguro_forzoso2);
            caja_ahorros2=String.valueOf(caja_ahorros);
            txtCajaAhorros.setText(caja_ahorros2);
            sueldo2=String.valueOf(sueldo);
            txtSueldoFinal.setText(sueldo2);
        }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCajaAhorros;
    private javax.swing.JTextField txtPolitica;
    private javax.swing.JTextField txtSeguroForzoso;
    private javax.swing.JTextField txtSeguroSocial;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtSueldoFinal;
    // End of variables declaration//GEN-END:variables
}
